### ISSUE TITLE
Vatican City flag is missing

### ISSUE THREAD

**Issue by adrianegger** [Yummygum/flagpack-core#17]
## Detailed Description
Can't have that, now can we? 😀

**Comment by donovanroubos** [comment]
We've chosen to use the `ISO 3166` standards and have therefore used the name _Holy See_ instead of _Vatican City_. More information about this [here](https://www.ip2location.com/VA/Holy_See). We're thinking about a new feature where you can use aliases. For example: Searching for `Europe` flags will show all flags that are within the European Union. So you can also use `Vatican` or `Vatican City` for the `Holy See` flag.

**Comment by noudadrichem** [comment]
This could easily be done by adding e.g. region tags to flags objects inside the index.
