### ISSUE TITLE
Kurdish flag is missing

### ISSUE THREAD

**Issue by erikfiala** [Yummygum/flagpack-core#20]
Not really a country per se (associated with 🇮🇷), but my colleague would love it, I'm sure. 🙂

**Comment by zvictor** [comment]
Related:
* [change.org petition](https://www.change.org/p/kurdistan-flag-emoji-aa37c7e6-0d24-44f9-ab27-8a1e5a0c1455)
* https://github.com/Crissov/unicode-proposals/issues/117

**Comment by donovanroubos** [comment]
Hi @erikfiala and @zvictor 👋

Currently we are working on standardizing the criteria for flags to be included and added to Flagpack. We'll share an update in the upcoming weeks about that.

**Comment by daoneandonly** [comment]
Flagpack uses the officially assigned ISO country codes as the source of truth. Because of this some flags might not be included in Flagpack. Please refer to the officially assigned country codes on the ISO website to see which Flags should be included in Flagpack.

We would like to note that the flag(s) you're suggesting do not align with the officially assigned ISO country codes and therefore will not be added to Flagpack. We're sorry for the inconvenience this may cause.
