### ISSUE TITLE
Tunisian flag

### ISSUE THREAD

**Issue by ram-you** [Yummygum/flagpack-core#22]
Hi, let me point out to you that the Tunisian flag (**TN**) does not meet the standard. 
Here the correct values.
Thank you. 

**Your wrong one:**
![WRONG](https://user-images.githubusercontent.com/3125972/105323291-40959b80-5bca-11eb-8809-7f6f66d080d5.png)

**The standard:**
COLORS= white + red  =  rgb(255, 255, 255) +  rgb(206, 17, 38)

![Drapeau_Tunisie](https://user-images.githubusercontent.com/3125972/105320515-8c464600-5bc6-11eb-8864-498b43d6ec1b.png)

![Drapeau_Tunisie_2](https://user-images.githubusercontent.com/3125972/105320970-20181200-5bc7-11eb-9640-0271aa43db1e.png)

**Comment by donovanroubos** [comment]
Hi @ram-you 👋 

_Als we've already mentioned via Twitter:_

We'll look into it. Please note that some flags are intentially somewhat diverted from the most realistic depiction to accomodate being recognizable and scannable on a small scale (to be used in dropdowns for example)

**Comment by daoneandonly** [comment]
It's important to note that (country) flags are inherently not designed to be displayed on an icon size or a size that is similarly small. We have come to the decision to not alter this flag any further. Flagpack has very minor stylistic changes in order to improve readibility on smaller sizes and some rare cases that might conflict with specific flag guidelines.
