### ISSUE TITLE
Algeria & Kosovo missing

### ISSUE THREAD

**Issue by irfancoder** [Yummygum/flagpack-core#27]
Algeria & Kosovo missing

Thanks for the library guys. If you guys do territories, please also consider:
- Ceuta Melila
- Mayotte
- Clipperton Island
- Diego Garcia
- Canary Islands

**Comment by ferdinanddoremus** [comment]
+1 for this one !
I really want to implement your work to handle flags on our apps at Ulysse.travel, but Algeria (DZ) is missing and we have a strong community from there here in France.
Please let us know !

**Comment by daoneandonly** [comment]
Flagpack uses the officially assigned ISO country codes as the source of truth. Because of this some flags might not be included in Flagpack. Please refer to the officially assigned country codes on the ISO website to see which Flags should be included in Flagpack.

We would like to note that the flag(s) you're suggesting do not align with the officially assigned ISO country codes and therefore will not be added to Flagpack. We're sorry for the inconvenience this may cause.
