### ISSUE TITLE
Other relevant flags to consider inclusion

### ISSUE THREAD

**Issue by pagelab** [Yummygum/flagpack-core#28]
Please consider adding also:

- [Basque Country](https://en.wikipedia.org/wiki/Basque_Country_(greater_region))
- [Catalonia](https://en.wikipedia.org/wiki/Catalonia)
- [Galicia](https://en.wikipedia.org/wiki/Galicia_(Spain))
- [Kurdistan](https://en.wikipedia.org/wiki/Flag_of_Kurdistan)
- [Tibet](https://en.wikipedia.org/wiki/Flag_of_Tibet)
- [Veneto](https://en.wikipedia.org/wiki/Veneto)
- [Occitania](https://en.wikipedia.org/wiki/Occitania)
- [Quebec](https://en.wikipedia.org/wiki/Quebec)
- [Esperanto](https://en.wikipedia.org/wiki/Esperanto)
- [Arab League](https://en.wikipedia.org/wiki/Arab_League)

**Comment by daoneandonly** [comment]
Flagpack uses the officially assigned ISO country codes as the source of truth. Because of this some flags might not be included in Flagpack. Please refer to the officially assigned country codes on the ISO website to see which Flags should be included in Flagpack.

We would like to note that the flag(s) you're suggesting do not align with the officially assigned ISO country codes and therefore will not be added to Flagpack. We're sorry for the inconvenience this may cause.
