### ISSUE TITLE
Arabic flag

### ISSUE THREAD

**Issue by lukaszflorczak** [Yummygum/flagpack-core#39]
Hey guys!

First, thank you for the amazing flag pack! I've started to use it in some projects but I found an important issue for me (and probably other users). I use the flags in the app language switcher so I found a problem with a flag for the Arabic language which is colocated with many countries. Could you add to the pack flag like that one? => https://commons.wikimedia.org/wiki/File:Flag_of_the_Arabic_language.svg

Thanks in advance

**Comment by Aareksio** [comment]
Before this issue gets dismissed as a flag for a country not defined in ISO-3166, this did not prevent you from including `AFRUN`, `AMS`, `RAINBOW` and `UNASUR` flags. Despite not being the best i18n practice, the flags (including ones provided by flagpack) are often used to describe languages. Arabic is spoken by more than 300 milion people worldwide - if `RAINBOW` deserves it's own flag, so does Arabic. Let's not ignore the issues only because we, living in english-first part of the world, are not directly affected.

**Comment by daoneandonly** [comment]
Hi @lukaszflorczak and @Aareksio. Thanks for your feedback on Flagpack!🙌

Flagpack is collection of country flags and therefore we have no current plans to include flags that represent languages. Currently we are working toward making Flagpack completely based on `ISO-3166`. This will mean that in the upcoming major version of Flagpack, flags such as `AMS`, `RAINBOW` and `AFRUN` will be removed. This is a recent decision we made regarding other flag requests. 

We regret not being able to offer you the flags that you request but we hope you can understand the policy we chose to decide which flags are included in Flagpack.

**Comment by Aareksio** [comment]
Thank you for the response. Clarifying you only recently decided to use ISO-3166 as the source of truth justifies the decision. Reading other issues, I haven't found any information as for why there are existing exceptions. Thank you!
