### ISSUE TITLE
Cat flag is missing

### ISSUE THREAD

**Issue by jbrinx** [Yummygum/flagpack-core#56]
Catalunya flag is missing

You can find information here 
https://ca.m.wikipedia.org/wiki/Bandera_de_Catalunya

**Comment by vicktor** [comment]
more info https://en.wikipedia.org/wiki/Senyera

**Comment by daoneandonly** [comment]
Flagpack uses the officially assigned ISO country codes as truth. Because of this some flags might not be included in Flagpack. Please refer to the officially assigned country codes on [the ISO website](https://www.iso.org/obp/ui/#home) to see which flags should be included in Flagpack.

We would like to note that the flag(s) you're suggesting do not align with the officially assigned ISO country codes and therefore will not be added to Flagpack. We're sorry for the inconvenience this may cause.
