### ISSUE TITLE
No flag for Kosovo.

### ISSUE THREAD

**Issue by arriaowlia** [Yummygum/flagpack-core#96]
There is no flag for Kosovo (XK / https://en.wikipedia.org/wiki/Kosovo). 

## Detailed Description
I propose the Kosovo flag be added to the repository.

## Is your feature request related to a problem? Please describe.
This is a great resource for flags, and it would be made even better with the addition of the Kosovo flag.

## Describe the solution you'd like
I'd like the ability to pass the XK code and see the Kosovo flag appear in my application.

## Describe alternatives you've considered
Alternatives would involve bespoke patterns for this specific instance.

## Additional context
Posting this issue under the direction of the Flagpack FAQ (https://flagpack.xyz/support).

**Comment by zoeyfrisart** [comment]
Hi @arriaowlia

Flagpack uses the officially assigned ISO country codes as truth. Because of this some flags might not be included in Flagpack. Please refer to the officially assigned country codes on [the ISO website](https://www.iso.org/obp/ui/#home) to see which flags should be included in Flagpack.

We would like to note that the flag(s) you're suggesting do not align with the officially assigned ISO country codes and therefore will not be added to Flagpack. We're sorry for the inconvenience this may cause.

Once Kosovo reaches an ISO 3166-1 status we will add the flag to Flagpack.

**Comment by Alexjjsmith** [comment]
Agreed, it's an exception included by Mapbox also, and google display the flag when you search for Kosovo

**Comment by reececomo** [comment]
@Alexjjsmith or @arriaowlia if you fork `flagpack-core` to include [Kosovo](https://commons.wikimedia.org/wiki/File:Flag_of_Kosovo.svg), let us know and we'll move our orgs to your new version of `flagpack-core`
